[package]
name = "plc14500_flash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.3.0"
log = "0.4.21"
tokio = { version = "1", features = ["full"]}
